#!/usr/bin/env python3.5

import spotify_playlist
import sys

source_one = spotify_playlist.Playlist(url="{}".format(sys.argv[1]))
print("[+] Created playlist one....")

source_two = spotify_playlist.Playlist(url="{}".format(sys.argv[2]))
print("[+] Created playlist two....")

new_playlist_name = "playlist_flask"

manager = spotify_playlist.PlaylistManager()
if(manager.is_playlist(new_playlist_name)):
	destination = spotify_playlist.Playlist(url="{}".format(manager.get_playlist_url(new_playlist_name)))
else:
	destination = spotify_playlist.Playlist.from_playlists(new_playlist_name, source_one, source_two)

print("[+] Created destination")
manager.truncate_playlist(destination)
print("[+] Truncating newly created playlist")
manager.append_to_playlist(destination, destination.track_ids)
print("[+] Added the contents of playlist one and playlist two")

