#!/usr/bin/env python3.5

import spotify_playlist

main_playlists= {
	"bree and amber and jared's robot": "https://open.spotify.com/user/12164553253/playlist/7715866mwpFJeZ6GkUK2Th?si=EG0FTH6bTWWYJKIyc3agxA",
	"2000's Rock": "https://open.spotify.com/user/believe556/playlist/4ccEeq0sbXWTHRecsFeDHg?si=fDW3FxeYTra_a6h8_lyj9Q"
}

source_one = spotify_playlist.Playlist(url="{}".format(main_playlists["bree and amber and jared's robot"]))
print("[+] Created playlist one....")
source_two = spotify_playlist.Playlist(url="{}".format(main_playlists["2000's Rock"]))
print("[+] Created playlist two....")
new_playlist_name = "bree and amber and jared's robot"
manager = spotify_playlist.PlaylistManager()
if(manager.is_playlist(new_playlist_name)):
	destination = spotify_playlist.Playlist(url="{}".format(manager.get_playlist_url(new_playlist_name)))
else:
	destination = spotify_playlist.Playlist.from_playlists(new_playlist_name, source_one, source_two)

print("[+] Created destination")
manager.truncate_playlist(destination)
print("[+] Truncating newly created playlist")
manager.append_to_playlist(destination, destination.track_ids)
print("[+] Added the contents of playlist one and playlist two")
